"""Macro language parser for template-based path generation."""

from griptape_nodes.common.macro_parser.core import ParsedMacro
from griptape_nodes.common.macro_parser.exceptions import (
    MacroMatchFailure,
    MacroMatchFailureReason,
    MacroParseFailure,
    MacroParseFailureReason,
    MacroResolutionError,
    MacroResolutionFailure,
    MacroResolutionFailureReason,
    MacroSyntaxError,
)
from griptape_nodes.common.macro_parser.formats import (
    AbbrevFormat,
    CamelCaseFormat,
    DateFormat,
    DotCaseFormat,
    LowerCaseFormat,
    NumericPaddingFormat,
    PascalCaseFormat,
    ScreamingSnakeCaseFormat,
    SeparatorFormat,
    SequenceFormat,
    SlugFormat,
    SnakeCaseFormat,
    TitleCaseFormat,
    TrimFormat,
    UpperCaseFormat,
)
from griptape_nodes.common.macro_parser.segments import (
    MacroVariables,
    ParsedStaticValue,
    ParsedVariable,
    VariableInfo,
)

__all__ = [
    "AbbrevFormat",
    "CamelCaseFormat",
    "DateFormat",
    "DotCaseFormat",
    "LowerCaseFormat",
    "MacroMatchFailure",
    "MacroMatchFailureReason",
    "MacroParseFailure",
    "MacroParseFailureReason",
    "MacroResolutionError",
    "MacroResolutionFailure",
    "MacroResolutionFailureReason",
    "MacroSyntaxError",
    "MacroVariables",
    "NumericPaddingFormat",
    "ParsedMacro",
    "ParsedStaticValue",
    "ParsedVariable",
    "PascalCaseFormat",
    "ScreamingSnakeCaseFormat",
    "SeparatorFormat",
    "SequenceFormat",
    "SlugFormat",
    "SnakeCaseFormat",
    "TitleCaseFormat",
    "TrimFormat",
    "UpperCaseFormat",
    "VariableInfo",
]
