"""Default project templates defined in Python using Pydantic models.

There is one default template per schema MAJOR version. A project merges onto the
default whose major matches its own declared `project_template_schema_version`, so a
breaking change to the defaults can land under a new major (v1) while existing v0
projects keep the old baseline. `default_template_for_version` is the single selector;
`DEFAULT_PROJECT_TEMPLATE` aliases the latest major (the system defaults new projects get).
"""

import semver

from griptape_nodes.common.project_templates.directory import DirectoryDefinition
from griptape_nodes.common.project_templates.project import ProjectTemplate
from griptape_nodes.common.project_templates.situation import (
    BuiltInSituation,
    SituationFilePolicy,
    SituationPolicy,
    SituationTemplate,
)
from griptape_nodes.retained_mode.managers.artifact_providers.audio.audio_artifact_provider import (
    AudioArtifactProvider,
)
from griptape_nodes.retained_mode.managers.artifact_providers.image.image_artifact_provider import (
    ImageArtifactProvider,
)
from griptape_nodes.retained_mode.managers.artifact_providers.video.video_artifact_provider import (
    VideoArtifactProvider,
)

# v0 default (schema 0.x): the legacy baseline. File destinations are workspace-root
# relative and file_extension_directory routing is not applied. Frozen: existing
# projects keep these defaults so their on-disk layout never shifts under them. The
# latest v0 version is 0.5.2 (additive schema bump from main), which a saved v0 project
# rolls forward to; V1 below carries the new-major baseline.
DEFAULT_PROJECT_TEMPLATE_V0 = ProjectTemplate(
    project_template_schema_version="0.5.2",
    name="Default Project",
    description="System default configuration",
    directories={
        "inputs": DirectoryDefinition(
            name="inputs",
            path_macro="inputs",
            description="Files brought into the project — uploads, copies, and downloads.",
        ),
        "outputs": DirectoryDefinition(
            name="outputs",
            path_macro="outputs",
            description="Files generated by nodes during workflow execution.",
        ),
        "temp": DirectoryDefinition(
            name="temp",
            path_macro="temp",
            description="Temporary scratch files; safe to delete between runs.",
        ),
        "griptape-nodes-previews": DirectoryDefinition(
            name="griptape-nodes-previews",
            path_macro=".griptape-nodes-previews",
            description="Generated preview/thumbnail artifacts; mirrors source-file hierarchy.",
        ),
        "griptape-nodes-metadata": DirectoryDefinition(
            name="griptape-nodes-metadata",
            path_macro=".griptape-nodes-metadata",
            description="Sidecar metadata for project files; mirrors source-file hierarchy.",
        ),
        "griptape-nodes-thumbnails": DirectoryDefinition(
            name="griptape-nodes-thumbnails",
            path_macro=".griptape-nodes-thumbnails",
            description="Workflow thumbnail images shown in the UI.",
        ),
    },
    environment={},
    # images/videos are derived from their ArtifactProviders so the layout
    # taxonomy stays aligned with the formats those providers actually handle.
    # audio/text/python have no artifact providers today and are listed
    # explicitly.
    file_extension_directories={
        **dict.fromkeys(ImageArtifactProvider.get_supported_formats(), "images"),
        **dict.fromkeys(VideoArtifactProvider.get_supported_formats(), "videos"),
        # audio
        "mp3": "audio",
        "wav": "audio",
        "flac": "audio",
        "ogg": "audio",
        "m4a": "audio",
        "aac": "audio",
        # documents / text
        "txt": "text",
        "md": "text",
        "json": "text",
        "yaml": "text",
        "yml": "text",
        "csv": "text",
        # python
        "py": "python",
    },
    situations={
        BuiltInSituation.SAVE_FILE: SituationTemplate(
            name=BuiltInSituation.SAVE_FILE,
            description="Generic file save operation",
            macro="{file_name_base}{###?}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.CREATE_NEW,
                create_dirs=True,
            ),
            fallback=None,
        ),
        BuiltInSituation.COPY_EXTERNAL_FILE: SituationTemplate(
            name=BuiltInSituation.COPY_EXTERNAL_FILE,
            description="User copies external file to project",
            macro="{inputs}/{node_name?:_}{parameter_name?:_}{file_name_base}{###?}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.CREATE_NEW,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
        BuiltInSituation.DOWNLOAD_URL: SituationTemplate(
            name=BuiltInSituation.DOWNLOAD_URL,
            description="Download file from URL",
            macro="{inputs}/{sanitized_url}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.OVERWRITE,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
        BuiltInSituation.SAVE_NODE_OUTPUT: SituationTemplate(
            name=BuiltInSituation.SAVE_NODE_OUTPUT,
            description="Node generates and saves output",
            macro="{outputs}/{sub_dirs?:/}{node_name?:_}{file_name_base}{###?}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.CREATE_NEW,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
        BuiltInSituation.SAVE_GRIPTAPE_NODES_PREVIEW: SituationTemplate(
            name=BuiltInSituation.SAVE_GRIPTAPE_NODES_PREVIEW,
            description="Generate preview/thumbnail with preserved directory hierarchy",
            macro="{griptape-nodes-previews}/{drive_volume_mount?:/}{source_relative_path?:/}{source_file_name}.{preview_format}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.OVERWRITE,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
        BuiltInSituation.SAVE_STATIC_FILE: SituationTemplate(
            name=BuiltInSituation.SAVE_STATIC_FILE,
            description="Save static file to workflow-relative staticfiles directory. Required for projects using StaticFilesManager.save_static_file.",
            macro="{workflow_dir?:/}{static_files_dir}/{file_name_base}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.OVERWRITE,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
        BuiltInSituation.SAVE_GRIPTAPE_NODES_METADATA: SituationTemplate(
            name=BuiltInSituation.SAVE_GRIPTAPE_NODES_METADATA,
            description="Save sidecar metadata file with preserved directory hierarchy",
            macro="{griptape-nodes-metadata}/{source_relative_path?:/}{source_file_name}.json",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.OVERWRITE,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
        # Workflows save into the workspace root today for backward compatibility.
        # Migrating to a dedicated subdirectory is tracked in
        # https://github.com/griptape-ai/griptape-nodes/issues/2047.
        BuiltInSituation.SAVE_WORKFLOW: SituationTemplate(
            name=BuiltInSituation.SAVE_WORKFLOW,
            description="Save a workflow Python file, preserving any sub-directory hierarchy",
            macro="{workspace_dir}/{sub_dirs?:/}{file_name_base}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.OVERWRITE,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
        # Versioned workflow save: every save bumps the padded `{###}` slot, so
        # successive saves produce a sequence (foo_v001.py, foo_v002.py, ...). Selected
        # via SaveWorkflowRequest.create_versioned=True. The macro and CREATE_NEW policy
        # are user-customizable like any other situation.
        # https://github.com/griptape-ai/griptape-nodes-engine/issues/4945
        BuiltInSituation.CREATE_VERSIONED_WORKFLOW: SituationTemplate(
            name=BuiltInSituation.CREATE_VERSIONED_WORKFLOW,
            description="Save a new version of a workflow with a padded index suffix",
            macro="{workspace_dir}/{sub_dirs?:/}{file_name_base}_v{###}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.CREATE_NEW,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
        BuiltInSituation.SAVE_WORKFLOW_THUMBNAIL: SituationTemplate(
            name=BuiltInSituation.SAVE_WORKFLOW_THUMBNAIL,
            description="Save a workflow thumbnail image into the hidden workspace thumbnails directory",
            macro="{griptape-nodes-thumbnails}/{file_name_base}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.OVERWRITE,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_STATIC_FILE,
        ),
        BuiltInSituation.SAVE_FAILED_WORKFLOW: SituationTemplate(
            name=BuiltInSituation.SAVE_FAILED_WORKFLOW,
            description="Save a failed workflow snapshot for post-mortem debugging",
            macro="{workspace_dir}/failures/{file_name_base}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.CREATE_NEW,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_WORKFLOW,
        ),
        BuiltInSituation.SAVE_TEMP_FILE: SituationTemplate(
            name=BuiltInSituation.SAVE_TEMP_FILE,
            description="Save a temporary scratch file (e.g. intermediate processing artifacts)",
            macro="{temp}/{node_name?:_}{file_name_base}{###?}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.OVERWRITE,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
    },
)


# v1 default (schema 1.x): file destinations are workflow-relative ({workflow_dir?:/})
# and routed by file_extension_directory; adds 3d/splat extension categories. New
# projects get this baseline; v0 projects are unaffected (they merge onto V0 above).
DEFAULT_PROJECT_TEMPLATE_V1 = ProjectTemplate(
    project_template_schema_version="1.0.0",
    name="Default Project",
    description="System default configuration",
    directories={
        "inputs": DirectoryDefinition(
            name="inputs",
            path_macro="{workflow_dir?:/}inputs",
            description="Files brought into the project — uploads, copies, and downloads.",
        ),
        "outputs": DirectoryDefinition(
            name="outputs",
            path_macro="{workflow_dir?:/}outputs",
            description="Files generated by nodes during workflow execution.",
        ),
        "temp": DirectoryDefinition(
            name="temp",
            path_macro="{workflow_dir?:/}temp",
            description="Temporary scratch files; safe to delete between runs.",
        ),
        "griptape-nodes-previews": DirectoryDefinition(
            name="griptape-nodes-previews",
            path_macro=".griptape-nodes-previews",
            description="Generated preview/thumbnail artifacts; mirrors source-file hierarchy.",
        ),
        "griptape-nodes-metadata": DirectoryDefinition(
            name="griptape-nodes-metadata",
            path_macro="{workflow_dir?:/}.griptape-nodes-metadata",
            description="Sidecar metadata for project files; mirrors source-file hierarchy.",
        ),
        "griptape-nodes-thumbnails": DirectoryDefinition(
            name="griptape-nodes-thumbnails",
            path_macro=".griptape-nodes-thumbnails",
            description="Workflow thumbnail images shown in the UI.",
        ),
    },
    environment={},
    # images/videos/audio are derived from their ArtifactProviders so the layout
    # taxonomy stays aligned with the formats those providers actually handle.
    # text/python/3d/splat have no artifact providers today and are listed explicitly.
    file_extension_directories={
        **dict.fromkeys(ImageArtifactProvider.get_supported_formats(), "images"),
        **dict.fromkeys(VideoArtifactProvider.get_supported_formats(), "videos"),
        **dict.fromkeys(AudioArtifactProvider.get_supported_formats(), "audio"),
        # documents / text
        "txt": "text",
        "md": "text",
        "json": "text",
        "yaml": "text",
        "yml": "text",
        "csv": "text",
        # python
        "py": "python",
        # 3d
        "obj": "3d",
        "fbx": "3d",
        "stl": "3d",
        "gltf": "3d",
        "glb": "3d",
        "3ds": "3d",
        "dae": "3d",
        "usdz": "3d",
        "usda": "3d",
        "usd": "3d",
        "usdc": "3d",
        # splat
        "splat": "splat",
        "ksplat": "splat",
        "spz": "splat",
        "ply": "splat",
    },
    situations={
        BuiltInSituation.SAVE_FILE: SituationTemplate(
            name=BuiltInSituation.SAVE_FILE,
            description="Generic file save operation",
            macro="{file_name_base}{###?}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.CREATE_NEW,
                create_dirs=True,
            ),
            fallback=None,
        ),
        BuiltInSituation.COPY_EXTERNAL_FILE: SituationTemplate(
            name=BuiltInSituation.COPY_EXTERNAL_FILE,
            description="User copies external file to project",
            macro="{inputs}/{file_extension_directory?:/}{file_name_base}{###?}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.CREATE_NEW,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
        BuiltInSituation.DOWNLOAD_URL: SituationTemplate(
            name=BuiltInSituation.DOWNLOAD_URL,
            description="Download file from URL",
            macro="{inputs}/{file_extension_directory?:/}{sanitized_url}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.OVERWRITE,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
        BuiltInSituation.SAVE_NODE_OUTPUT: SituationTemplate(
            name=BuiltInSituation.SAVE_NODE_OUTPUT,
            description="Node generates and saves output",
            macro="{outputs}/{file_extension_directory?:/}{sub_dirs?:/}{file_name_base}_v{###}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.CREATE_NEW,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
        BuiltInSituation.SAVE_GRIPTAPE_NODES_PREVIEW: SituationTemplate(
            name=BuiltInSituation.SAVE_GRIPTAPE_NODES_PREVIEW,
            description="Generate preview/thumbnail with preserved directory hierarchy",
            macro="{griptape-nodes-previews}/{drive_volume_mount?:/}{source_relative_path?:/}{source_file_name}.{preview_format}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.OVERWRITE,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
        BuiltInSituation.SAVE_STATIC_FILE: SituationTemplate(
            name=BuiltInSituation.SAVE_STATIC_FILE,
            description="Save static file to workflow-relative staticfiles directory. Required for projects using StaticFilesManager.save_static_file.",
            macro="{workflow_dir?:/}{static_files_dir}/{file_name_base}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.OVERWRITE,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
        BuiltInSituation.SAVE_GRIPTAPE_NODES_METADATA: SituationTemplate(
            name=BuiltInSituation.SAVE_GRIPTAPE_NODES_METADATA,
            description="Save sidecar metadata file with preserved directory hierarchy",
            macro="{griptape-nodes-metadata}/{source_relative_path?:/}{source_file_name}.json",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.OVERWRITE,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
        # Workflows save into the workspace root today for backward compatibility.
        # Migrating to a dedicated subdirectory is tracked in
        # https://github.com/griptape-ai/griptape-nodes/issues/2047.
        BuiltInSituation.SAVE_WORKFLOW: SituationTemplate(
            name=BuiltInSituation.SAVE_WORKFLOW,
            description="Save a workflow Python file, preserving any sub-directory hierarchy",
            macro="{workspace_dir}/{sub_dirs?:/}{file_name_base}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.OVERWRITE,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
        # Versioned workflow save: every save bumps the padded `{###?:^_v}` slot, so
        # successive saves produce a sequence (foo_v001.py, foo_v002.py, ...). Selected
        # via SaveWorkflowRequest.create_versioned=True. The macro and CREATE_NEW policy
        # are user-customizable like any other situation.
        # https://github.com/griptape-ai/griptape-nodes-engine/issues/4945
        BuiltInSituation.CREATE_VERSIONED_WORKFLOW: SituationTemplate(
            name=BuiltInSituation.CREATE_VERSIONED_WORKFLOW,
            description="Save a new version of a workflow with a padded index suffix",
            macro="{workspace_dir}/{sub_dirs?:/}{file_name_base}{###?:^_v}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.CREATE_NEW,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
        BuiltInSituation.SAVE_WORKFLOW_THUMBNAIL: SituationTemplate(
            name=BuiltInSituation.SAVE_WORKFLOW_THUMBNAIL,
            description="Save a workflow thumbnail image into the hidden workspace thumbnails directory",
            macro="{griptape-nodes-thumbnails}/{file_name_base}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.OVERWRITE,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_STATIC_FILE,
        ),
        BuiltInSituation.SAVE_FAILED_WORKFLOW: SituationTemplate(
            name=BuiltInSituation.SAVE_FAILED_WORKFLOW,
            description="Save a failed workflow snapshot for post-mortem debugging",
            macro="{workspace_dir}/failures/{file_name_base}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.CREATE_NEW,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_WORKFLOW,
        ),
        BuiltInSituation.SAVE_TEMP_FILE: SituationTemplate(
            name=BuiltInSituation.SAVE_TEMP_FILE,
            description="Save a temporary scratch file (e.g. intermediate processing artifacts)",
            macro="{temp}/{node_name?:_}{file_name_base}{###?}.{file_extension}",
            policy=SituationPolicy(
                on_collision=SituationFilePolicy.OVERWRITE,
                create_dirs=True,
            ),
            fallback=BuiltInSituation.SAVE_FILE,
        ),
    },
)


# One default template per schema major. The selector below picks by a project's own
# declared major so a v0 project merges onto the v0 baseline and a v1 project onto v1.
_DEFAULT_TEMPLATE_BY_MAJOR: dict[int, ProjectTemplate] = {
    0: DEFAULT_PROJECT_TEMPLATE_V0,
    1: DEFAULT_PROJECT_TEMPLATE_V1,
}

# The latest-major default: the system-defaults baseline new projects are created against.
DEFAULT_PROJECT_TEMPLATE = DEFAULT_PROJECT_TEMPLATE_V1


def schema_major_or_none(version: str) -> int | None:
    """Parse a schema version's major, or None when the version is not valid semver.

    Project version strings are user-controlled (read verbatim from project.yml). Callers on
    the load path must not raise on a malformed value -- before the per-major fork existed, a
    bad version was never parsed and the project still loaded against the single default. None
    lets callers fall back to the latest default rather than crashing the load.
    """
    try:
        return semver.VersionInfo.parse(version).major
    except ValueError:
        return None


def default_template_for_version(version: str) -> ProjectTemplate:
    """Return the default (merge-base) ProjectTemplate matching a schema version's major.

    A project merges onto the default for its own major so a breaking defaults change can
    land under a new major without moving existing projects. An unknown major OR a malformed
    version falls back to the latest default (forward-compat: a project declaring a not-yet-known
    or unparsable version still loads against the newest baseline rather than failing).
    """
    major = schema_major_or_none(version)
    if major is None:
        return DEFAULT_PROJECT_TEMPLATE
    return _DEFAULT_TEMPLATE_BY_MAJOR.get(major, DEFAULT_PROJECT_TEMPLATE)


def latest_version_for_major(version: str) -> str | None:
    """Return the latest known schema version within a version's major, or None if unknown.

    Each per-major default template carries the latest version for its major (e.g. the v0
    default is pinned at the newest 0.x). The save policy targets this so a v0 project rolls
    forward to the latest 0.x on save (an additive within-major upgrade) without ever crossing
    to the next major. None for a major with no registered default, or a malformed version (no
    in-major target exists, so the caller leaves the version untouched).
    """
    major = schema_major_or_none(version)
    if major is None:
        return None
    template = _DEFAULT_TEMPLATE_BY_MAJOR.get(major)
    if template is None:
        return None
    return template.project_template_schema_version
